POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"quynh",
    "password":"quynh",
    
}
###
GET  http://localhost:5000/api/auth/
Content-Type: application/json

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"jim",
    "password":"jim"
}
###
POST http://localhost:5000/api/posts/
Content-Type: application/json
Authorization: Bearer fds.eyJ1c2VySWQiOiI2MGNlY2M3YmE1ZjYyYTJkYmU1MjhmMzIiLCJpYXQiOjE2MjQxNjU2OTl9.HrOdQ7ZzKUpC93YouNxweJc_YVTJlYSProsh7D-I1_Y

{
    "title":"Second asdad",
    "description":"bla bla bla",
    "url":"vuejs.com",
    "status":"LEARNING"
}
###

GET http://localhost:5000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGNlY2M3YmE1ZjYyYTJkYmU1MjhmMzIiLCJpYXQiOjE2MjQxNjU2OTl9.HrOdQ7ZzKUpC93YouNxweJc_YVTJlYSProsh7D-I1_Y
###
PUT http://localhost:5000/api/posts/60cecd4ea5f62a2dbe528f3c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGNlY2M3YmE1ZjYyYTJkYmU1MjhmMzIiLCJpYXQiOjE2MjQxNjU2OTl9.HrOdQ7ZzKUpC93YouNxweJc_YVTJlYSProsh7D-I1_Y

{
    "title":"Second asdad updated",
    "description":"updated",
    "url":"updated.com",
    "status":"TO LEARN"
}

###

DELETE  http://localhost:5000/api/posts/60ced372cabf843017a7f0cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGNlY2M3YmE1ZjYyYTJkYmU1MjhmMzIiLCJpYXQiOjE2MjQxNjU2OTl9.HrOdQ7ZzKUpC93YouNxweJc_YVTJlYSProsh7D-I1_Y
###

POST http://localhost:5000/api/products/
Content-Type: application/json

{
      "name": "Huawei nova 3i",
      "screen": "AMOLED",
      "cpu": "Exynos 2100",
      "ram": "8 GB",
      "rom": "128 GB",
      "img": "https://cdn.tgdd.vn/Products/Images/42/179673/huawei-nova-3i-600-600-600x600.jpg",
      "quantity": 4,
      "brand": "60d45b33df04e02b981fbb1d"
}
###
DELETE  http://localhost:5000/api/products/60d20600968e6a34ce589dd6
Content-Type: application/json
###
GET  http://localhost:5000/api/products/
Content-Type: application/json

###
PUT  http://localhost:5000/api/products/60d208109e2aeb36e0b71015
Content-Type: application/json

{
      "name": "Iphone 12",
      "screen": "AMOLED",
      "cpu": "A14 BIONIC",
      "ram": "6G",
      "rom": "64G",
      "img": "https://cdn.tgdd.vn/Products/Images/42/213031/iphone-12-violet-1-600x600.jpg",
      "quantity":10,
        "brand":"60d45b07df04e02b981fbb17"
}

###
POST http://localhost:5000/api/brands/
Content-Type: application/json

{
    "name":"huawei",
    "description":"Huawei"
}
###
POST http://localhost:5000/api/brands/
Content-Type: application/json

{
    "name":"huawei",
    "description":"Huawei"
}
###
GET http://localhost:5000/api/brands/
Content-Type: application/json
###
DELETE http://localhost:5000/api/brands/60d52857f36c77052ef4f91f
Content-Type: application/json

###
POST http://localhost:5000/api/customers/register
Content-Type: application/json

{
    "username":"vanson",
    "name":"Van Son",
    "password":"vanson",
    "phone":"0523391051",
    "address":"4 Nguyen Tat Thanh Quan 4 Tp HCM",
    "email":"son@gmail.com"
}
###
GET http://localhost:5000/api/customers/
Content-Type: application/json
###

PUT http://localhost:5000/api/customers/60e2dfddf2b5d613da53fb50
Content-Type: application/json

{
    "username":"vanson1",
    "name":"Van Son",
    "password":"vanson",
    "phone":"0523391051",
    "address":"4 Nguyen Tat Thanh Quan 4 Tp HCM",
    "email":"son@gmail.com"
}
###
POST http://localhost:5000/api/customers/login
Content-Type: application/json

{
    "username":"vanson",
    "password":"vanson"
}

###
DELETE http://localhost:5000/api/customers/60e2e12b85dabf14d5b932ae
Content-Type: application/json

###
POST http://localhost:5000/api/comments
Content-Type: application/json

{
    "customer":"60e31daf75f8a422ea7bd71e",
    "product":"60d724b2cf54f306327e9c9b",
    "content":"Huawei kia"
}
###
GET http://localhost:5000/api/customers/
Content-Type: application/json
###
GET  http://localhost:5000/api/products/
Content-Type: application/json
###

DELETE   http://localhost:5000/api/comments/60e44f585ee6cf1bba3ba376
Content-Type: application/json